[book]
authors = ["tmt514"]
multilingual = false
src = "src"
title = "演算法的分析與證明"

[output.html]
mathjax-support = true
no-section-label = true
additional-js = ["mathjax-config.js"]
additional-css = ["styles/mdbook.css"]

[output.html.fold]
enable = true
level = 1

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 3

[preprocessor.mathjax_dollar_sign]
command = "python3 mathjax-support.py"
renderer = ["html", "epub"]

[output.html.playground]
editable = true